export const KYC_TYPES = {
  INDIVIDUAL: 'INDIVIDUAL',
  BUSINESS: 'BUSINESS',
}

export const KYC_STATUSES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  PENDING_COMPLIANCE: 'PENDING_COMPLIANCE',
  APPROVED: 'APPROVED',
  RESUBMISSION_REQUIRED: 'RESUBMISSION_REQUIRED',
  RETURNED_TO_REVIEWER: 'RETURNED_TO_REVIEWER',
}

export const CLIENT_EDITABLE_STATUSES = new Set([
  KYC_STATUSES.DRAFT,
  KYC_STATUSES.RESUBMISSION_REQUIRED,
])

export const CLIENT_OPEN_REQUEST_STATUSES = new Set([
  KYC_STATUSES.DRAFT,
  KYC_STATUSES.SUBMITTED,
  KYC_STATUSES.PENDING_COMPLIANCE,
  KYC_STATUSES.RETURNED_TO_REVIEWER,
  KYC_STATUSES.RESUBMISSION_REQUIRED,
])
